<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.ApplicaionLayer\ECommerce.ApplicaionLayer.csproj" />
    <ProjectReference Include="..\ECommerce.Inferastructure\ECommerce.Inferastructure.csproj" />
  </ItemGroup>

</Project>
